spring:
  application:
    name: LibraryProject
    datasource:
      url: jdbc:postgresql://localhost:5432/library
      username: postgres
      password: 1234
      database:
          driverClassName: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true


